name: Legacy Import Guard
description: Fail if deprecated shared_python imports are present outside allowed wrapper directory or tests.
runs:
  using: composite
  steps:
    - name: Run legacy import scan
      shell: bash
      run: |
        python - <<'PY'
        import pathlib, re, sys
        ROOT = pathlib.Path('.')
        allowed = ROOT / 'shared' / 'shared_python'
        pattern = re.compile(r'^\s*(from|import)\s+shared_python(\.|\s|$)')
        violations = []
        for py in ROOT.rglob('*.py'):
            if allowed in py.parents: continue
            if 'test' in py.name.lower(): continue
            try:
                text = py.read_text(encoding='utf-8', errors='ignore')
            except Exception:
                continue
            for i,l in enumerate(text.splitlines(),1):
                if pattern.search(l):
                    violations.append(f"{py}:{i}:{l.strip()}")
        if violations:
            print('Legacy shared_python imports detected:')
            for v in violations:
                print('  '+v)
            sys.exit(1)
        print('No legacy shared_python imports.')
        PY
